services:
  mossy:
    build: .
    profiles:
      - dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://username:password@postgres:5432/dbname
      REDIS_URL: redis://:password@redis:6379/0
      WEBAUTHN_RP_SOURCE: http://localhost:8000
      WEBAUTHN_RP_ID: localhost
      LOG_LEVEL: debug
      SERVICE_MODE: all
      WORKERS: 2
    container_name: mossy-app
    hostname: mossy-app

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    container_name: mossy-postgres
    hostname: mossy-postgres
    ports:
      - "5432:5432"

  # Garnet is a Redis-compatible in-memory key-value store. Not support all commands.
  # garnet:
  #   image: ghcr.io/microsoft/garnet
  #   command: --auth Password --password password
  #   container_name: mossy-garnet
  #   hostname: mossy-garnet
  #   ulimits:
  #     memlock: -1
  #   ports:
  #     - "6379:6379"

  redis:
    image: redis
    command: ["redis-server", "--requirepass", "password"]
    container_name: mossy-redis
    hostname: mossy-redis
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
